/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_call_InitJNI */

#ifndef _Included_com_example_call_InitJNI
#define _Included_com_example_call_InitJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_call_InitJNI
 * Method:    init
 * Signature: (Landroid/content/Context;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_call_InitJNI_init
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
